models:
  - name: dim_customers
    description: >
     customer dimension table in scd2 format. 
     This is a silver layer for customer data. 
     This is a cleaned, deduplicated, and standardized but not yet aggregated for business reporting.
     This has change data capture (CDC) implemented using SCD2 methodology to track historical changes in customer data.
    columns:
      - name: cust_id
        data_type: varchar
        description: "cust_id is a unique identifier for each customer system generated"

      - name: cust_no
        data_type: varchar
        description: "this is a unique customer number assigned to each customer by the bank"

      - name: cust_name
        data_type: varchar
        description: "customer's full name"

      - name: cust_join_date
        data_type: date
        description: "customer's join date"

      - name: record_date
        data_type: date
        description: "date when the record was created or last updated"

      - name: row_hash
        data_type: varchar
        description: "row_hash created on a combination of fields in check_cols cust_no, cust_name, cust_join_date, is_retail_cust to identify changes in data"

      - name: dbt_valid_from
        data_type: date
        description: "record valid from date"

      - name: dbt_valid_to
        data_type: date
        description: "record valid to date"

      - name: dbt_delete_flag
        data_type: integer
        description: "is record maked for deletion?"

      - name: dbt_updated_at
        data_type: timestamp(6) with time zone
        description: "last updated timestamp"

  - name: dim_accounts
    description: >
      account dimension table in scd2 format. 
      This is a silver layer for accounts data. 
      This is a cleaned, deduplicated, and standardized but not yet aggregated for business reporting.
      This has change data capture (CDC) implemented using SCD2 methodology to track historical changes in accounts data.
    columns:
      - name: acct_id
        data_type: varchar
        description: "acct_id is a unique identifier for each account"

      - name: acct_no
        data_type: varchar
        description: "acct_no is a unique account number assigned to each account by the bank"

      - name: product
        data_type: varchar
        description: "Product type of the account - Savings, Checking, Credit Card, Loan etc."

      - name: sub_product
        data_type: varchar
        description: "Product sub type of the account - e.g. for Savings product, sub_product can be Standard Savings, Premium Savings etc."

      - name: is_actv
        data_type: varchar
        description: "is the account active?"

      - name: retail_acct
        data_type: varchar
        description: "is this a retail account? (An account is a retail account if it is mapped to a retail product)"

      - name: holding_type
        data_type: varchar
        description: "Mode of holding of the account - Single, Joint, Corporate etc."

      - name: acct_open_date
        data_type: date
        description: "account open date"

      - name: record_date
        data_type: date
        description: "date when the record was created or last updated"

      - name: row_hash
        data_type: varchar
        description: "row_hash created on a combination of fields in check_cols acct_no, product, sub_product, is_actv, retail_acct, holding_type, acct_open_date to identify changes in data"

      - name: dbt_valid_from
        data_type: date
        description: "record valid from date"

      - name: dbt_valid_to
        data_type: date
        description: "record valid to date"

      - name: dbt_delete_flag
        data_type: integer
        description: "is record marked for deletion?"

      - name: dbt_updated_at
        data_type: timestamp(6) with time zone
        description: "last updated timestamp"

  - name: fact_transactions
    description: "transaction fact table in scd2 format"
    columns:
      - name: tran_id
        data_type: varchar
        description: "tran_id is a unique identifier for each transaction"

      - name: acct_id
        data_type: varchar
        description: "acct_id is a unique identifier for each account.This should map to dim_accounts.acct_id field to get which account the transaction belongs to."

      - name: tran_type
        data_type: varchar
        description: "Is is a credit or debit transaction?"

      - name: amount
        data_type: double
        description: "transaction amount"

      - name: tran_date
        data_type: date
        description: "date of the transaction posting"

      - name: record_date
        data_type: date
        description: "record date when the transaction record was created or last updated"

      - name: row_hash
        data_type: varchar
        description: "row_hash created on a combination of fields in check_cols acct_id, tran_type, amount, tran_date to identify changes in data"

      - name: dbt_valid_from
        data_type: date
        description: "record valid from date"

      - name: dbt_valid_to
        data_type: date
        description: "record valid to date"

      - name: dbt_delete_flag
        data_type: integer
        description: "is record marked for deletion?"

      - name: dbt_updated_at
        data_type: timestamp(6) with time zone
        description: "last updated timestamp"

  - name: bridge_cust_acct
    description: "bridge table mapping customers to their accounts"
    columns:
      - name: cust_id
        data_type: varchar
        description: "cust_id is a unique identifier for each customer. This should map to dim_customers.cust_id field to get which customer the account belongs to."

      - name: acct_id
        data_type: varchar
        description: "acct_id is a unique identifier for each account. This should map to dim_accounts.acct_id field to get which account belongs to which customer."

      - name: record_date
        data_type: date
        description: "record date when the bridge record was created or last updated"

      - name: row_hash
        data_type: varchar
        description: "row_hash created on a combination of fields in check_cols cust_id, acct_id to identify changes in data"

      - name: dbt_valid_from
        data_type: date
        description: "record valid from date"

      - name: dbt_valid_to
        data_type: date
        description: "record valid to date"

      - name: dbt_delete_flag
        data_type: integer
        description: "is record marked for deletion?"

      - name: dbt_updated_at
        data_type: timestamp(6) with time zone
        description: "last updated timestamp"