version: 0.2

env:
  secrets-manager:
    TRINO_URL: "prod/dbt/starburst:TRINO_URL"
    DBT_TRINO_USER: "prod/dbt/starburst:DBT_TRINO_USER"
    DBT_TRINO_PASSWORD: "prod/dbt/starburst:DBT_TRINO_PASSWORD"
    DBT_SCHEMA: "prod/dbt/starburst:DBT_SCHEMA"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - export PYTHONWARNINGS="ignore:Unverified HTTPS request"
      - echo "Installing dbt..."
      - pip install dbt-core dbt-starburst
  build:
    commands:
      - echo "Entering project directory..."
      - cd cust_tran
      
      # FIX 1: Wrap this entire line in single quotes so YAML doesn't break
      - 'RUN_DATE="${BUSINESS_DATE:-$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m-%d)}"'
      
      - echo "------------------------------------------------"
      - echo "Processing Data For Business Date: $RUN_DATE"
      - echo "------------------------------------------------"
      
      - dbt deps --profiles-dir .
      
      # FIX 2: Wrap this entire line in single quotes too (because of the JSON colons)
      - 'dbt run --profiles-dir . --vars "{\"business_date\": \"$RUN_DATE\"}"'