version: 0.2

env:
  variables:
    # 1. Define your Glue Job Name here
    GLUE_JOB_NAME: "json_to_parquet"
    # Default to false. You can override this in CodeBuild "Start Build" options
    RESET_BOOKMARK: "false"
  secrets-manager:
    TRINO_URL: "prod/dbt/starburst:TRINO_URL"
    DBT_TRINO_USER: "prod/dbt/starburst:DBT_TRINO_USER"
    DBT_TRINO_PASSWORD: "prod/dbt/starburst:DBT_TRINO_PASSWORD"
    DBT_SCHEMA: "prod/dbt/starburst:DBT_SCHEMA"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Checking python version..."
      - python --version
      - pip install --upgrade pip
      - pip install "urllib3<2.0"
      - pip install "protobuf>=4.21.1,<5.0.0"

      # 3. Install specific versions of dbt-core and dbt-trino
      - pip install dbt-core==1.7.4 dbt-trino==1.7.1

  build:
    commands:
      - echo "Verifying installations..."
      - dbt --version
      - echo "dbt build process starting..."
      - cd cust_tran
      # ----------------------------------------------------------------
      # STEP 1: TRIGGER AWS GLUE JOB (BLOCKING)
      # ----------------------------------------------------------------
      - echo "Triggering Glue Job: $GLUE_JOB_NAME with Bookmark Reset: $RESET_BOOKMARK"
      # Start the job and capture the Run ID. 
      # We pass the bookmark reset as a job argument "--reset_bookmark"
      - |
        JOB_RUN_ID=$(aws glue start-job-run \
          --job-name "$GLUE_JOB_NAME" \
          --arguments="--reset_bookmark=${RESET_BOOKMARK}" \
          --query 'JobRunId' \
          --output text)
      - echo "Glue Job started. Run ID: $JOB_RUN_ID. Waiting for completion..."
      # Poll the status every 15 seconds until SUCCEEDED or FAILED
      - |
        while :; do
          STATUS=$(aws glue get-job-run --job-name "$GLUE_JOB_NAME" --run-id "$JOB_RUN_ID" --query 'JobRun.JobRunState' --output text)
          echo "Current Glue Job Status: $STATUS"
          if [ "$STATUS" == "SUCCEEDED" ]; then
            echo "Glue Job finished successfully! Proceeding to dbt..."
            break
          elif [ "$STATUS" == "FAILED" ] || [ "$STATUS" == "STOPPED" ] || [ "$STATUS" == "TIMEOUT" ]; then
            echo "Error: Glue Job failed. Stopping build."
            exit 1
          fi
          sleep 15
        done
      # ----------------------------------------------------------------
      # STEP 2: DBT TRANSFORMATION
      # ----------------------------------------------------------------
      - export RUN_DATE=$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m-%d)
      - echo "------------------------------------------------"
      - 'echo "Processing Data For Business Date: $RUN_DATE"'
      - echo "------------------------------------------------"
      - dbt clean 
      - dbt deps
      - dbt run-operation force_create_external_tables
      - "dbt run --select models/core --vars '{\"initial_load\": true}'"
      - "dbt run --select models/gold --vars \"{\\\"business_date\\\": \\\"$RUN_DATE\\\"}\""
      - dbt run --select models/consumption_views
