version: 0.2

env:
  # We will map these in the AWS Console later
  secrets-manager:
    TRINO_URL: "prod/dbt/starburst:TRINO_URL"
    DBT_TRINO_USER: "prod/dbt/starburst:DBT_TRINO_USER"
    DBT_TRINO_PASSWORD: "prod/dbt/starburst:DBT_TRINO_PASSWORD"
    DBT_SCHEMA: "prod/dbt/starburst:DBT_SCHEMA"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - export PYTHONWARNINGS="ignore:Unverified HTTPS request"
      - echo "Installing dbt and Starburst adapter..."
      - pip install dbt-core dbt-trino
  build:
    commands:
      - echo "Entering project directory..."
      - cd cust_tran
      # ---------------------------------------------------------
      # DATE LOGIC:
      # 1. If BUSINESS_DATE env var exists (Manual Override), use it.
      # 2. Else, calculate 1st day of previous month.
      # ---------------------------------------------------------
      - RUN_DATE="${BUSINESS_DATE:-$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m-%d)}"
      
      - echo "------------------------------------------------"
      - echo "Processing Data For Business Date: $RUN_DATE"
      - echo "------------------------------------------------"
      - echo "Starting dbt run..."
      # This assumes your profiles.yml is in the root. 
      # If it's in a folder, cd into it first.
      - dbt deps --profiles-dir .
      - dbt debug --profiles-dir .
      - dbt run --profiles-dir . --vars "{\"business_date\": \"$RUN_DATE\"}"