version: 0.2

env:
  secrets-manager:
    TRINO_URL: "prod/dbt/starburst:TRINO_URL"
    DBT_TRINO_USER: "prod/dbt/starburst:DBT_TRINO_USER"
    DBT_TRINO_PASSWORD: "prod/dbt/starburst:DBT_TRINO_PASSWORD"
    DBT_SCHEMA: "prod/dbt/starburst:DBT_SCHEMA"

phases:
  install:
    runtime-versions:
      # CodeBuild expects just Major.Minor here. 
      # It will pull the latest 3.11.x (likely 3.11.9 or newer).
      python: 3.11
    commands:
      - echo "Checking python version..."
      - python --version
      
      # 1. Upgrade pip to ensure the fastest dependency resolver
      - pip install --upgrade pip

      
      # 2. VITAL FIX: Pin urllib3 < 2.0 to stop the dependency loop
      # dbt-core 1.7.x dependencies still require older urllib3
      - pip install "urllib3<2.0"
      - pip install "protobuf>=4.21.1,<5.0.0"

      # 3. Install specific versions of dbt-core and dbt-trino
      - pip install dbt-core==1.7.4 dbt-trino==1.7.1

  build:
    commands:
      - echo "Verifying installations..."
      - dbt --version
      - echo "dbt build process starting..."
      - cd cust_tran
      
      # FIX 1: Export needs to be available to current shell execution
      - export RUN_DATE=$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m-%d)
      
      - echo "------------------------------------------------"
      - echo "Processing Data For Business Date: $RUN_DATE"
      - echo "------------------------------------------------"
      - dbt clean 
      - dbt deps
      - dbt run-operation force_create_external_tables
      
      # FIX 2 & 3: Wrapped in double quotes for YAML, removed 'echo'/'backticks'
      - "dbt run --select models/core --vars '{\"initial_load\": true}'"
      
      # FIX 4: Correct quoting to allow $RUN_DATE variable expansion
      - "dbt run --select models/gold --vars \"{\\\"business_date\\\": \\\"$RUN_DATE\\\"}\""
      
      - dbt run --select models/consumption_views
